# Generated by Django 5.0.1 on 2024-01-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updatedDate",
                    models.DateField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdDate",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Hayvan Sınıfı Adı"
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
            options={
                "verbose_name": "Hayvan Sınıfı",
                "verbose_name_plural": "Hayvan Sınıfları",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updatedDate",
                    models.DateField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdDate",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sayfalarda değiştirilmesi istenen alanların ayarlarının adı buradan yapılır.",
                        max_length=255,
                        verbose_name="Genel Ayar Adı",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kullanılacak yerin neresi olduğuna dair açıklama",
                        max_length=255,
                        verbose_name="Genel Ayar Adı",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kullanılacak yerin alacağı parametre adı",
                        max_length=255,
                        verbose_name="Parametre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genel Ayar",
                "verbose_name_plural": "Genel Ayarlar",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updatedDate",
                    models.DateField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdDate",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Hayvan Adı")),
                ("slug", models.SlugField(unique=True)),
                (
                    "img",
                    models.ImageField(
                        null=True, upload_to="animals", verbose_name="Hayvan Resmi"
                    ),
                ),
                (
                    "animalClass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hayvanlar.animalclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
