# Generated by Django 5.0.1 on 2024-01-21 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hayvanlar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={
                "ordering": ("name",),
                "verbose_name": "Hayvan Sınıfı",
                "verbose_name_plural": "Hayvan Sınıfları",
            },
        ),
    ]
