# Generated by Django 5.0.1 on 2024-01-21 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hayvanlar", "0002_alter_animal_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={
                "ordering": ("name",),
                "verbose_name": "Hayvan",
                "verbose_name_plural": "Hayvanlar",
            },
        ),
    ]
